name: dreamingbluesky
favicon: null
layout_spectrum: 0.50426
typography_spectrum: 0.43796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a1978e'
    - '#1d2731'
    - '#4c5223'
    - '#bc6819'
    - '#d4e1e7'
  brandStrength: 0.3125
  lightness: 0.3459486663341522
  saturation: 0.5226588554214686
  rhythmicContrast: 0.3710581650957465
purpose: []
